package co.poli.ppi.gui;

import co.poli.ppi.entidades.Anotacion;
import co.poli.ppi.lista.ListaRegistro;
import javax.swing.JOptionPane;

/**
 * Declaración de la clase interfaz RegistroDeAnotacion
 *
 * @author Juan David Cobos Cano
 * @version 9/07/17
 */
public class RegistroDeAnotacion extends javax.swing.JFrame {

    /**
     * Creación de la lista
     */
    ListaRegistro listaregistro = new ListaRegistro();

    /**
     * Creación del método para insertar en la lista
     */
    public Anotacion crearAnotacion() {
        ValidarCampos();
        int codigo;
        String nombreEstudiante, nombreDocente, descripcion, descargos, fecha, tipo;

        fecha = jcbFecha.getSelectedItem().toString();
        tipo = jcbTipo.getSelectedItem().toString();
        codigo = Integer.parseInt(txtCodigo.getText());
        nombreEstudiante = txtnombreEstudiante.getText();
        nombreDocente = txtnombreDocente.getText();
        descripcion = txtaDescripcion.getText();
        descargos = txtaDescargos.getText();

        Anotacion anotacion = new Anotacion(codigo, nombreEstudiante, nombreDocente, descripcion, descargos, fecha, tipo);
        this.limpiarCampos();
        return anotacion;
    }

    /**
     * Método para limpiar los campos de registro de la anotación
     */
    public void limpiarCampos() {
        jcbFecha.setSelectedItem(" ");
        jcbTipo.setSelectedItem(" ");
        txtCodigo.setText("");
        txtnombreEstudiante.setText("");
        txtnombreDocente.setText("");
        txtaDescripcion.setText("");
        txtaDescargos.setText("");

    }

    /**
     * Método para validar los campos del registro de anotación
     */
    public boolean ValidarCampos() {
        boolean val = true;
        /* *Este método es para validar los campos, para asegurarse que el
         * usuario sí ingrese los campos obligatorios
         */

        String nombreEstudiante, nombreDocente, descripcion, descargos, fecha, tipo, codigo;

        fecha = jcbFecha.getSelectedItem().toString();
        tipo = jcbTipo.getSelectedItem().toString();
        codigo = txtCodigo.getText();
        nombreEstudiante = txtnombreEstudiante.getText();
        nombreDocente = txtnombreDocente.getText();
        descripcion = txtaDescripcion.getText();
        descargos = txtaDescargos.getText();
//aqui se identifica si algun campo no esta lleno
        //se indicara que se debe llenar el campo 
        if (fecha.length() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione la fecha ");
            jcbFecha.requestFocus();
            val = false;
//aqui se identifica si algun campo no esta lleno
            //se indicara que se debe llenar el campo 
        } else if (tipo.length() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione el tipo de falta");
            jcbTipo.requestFocus();
            val = false;
//aqui se identifica si algun campo no esta lleno
            //se indicara que se debe llenar el campo 
        } else if (nombreDocente.length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese el nombre completo del docente");
            txtnombreDocente.requestFocus();
            val = false;
//aqui se identifica si algun campo no esta lleno
            //se indicara que se debe llenar el campo 
        } else if (nombreEstudiante.length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese el nombre completo del estudiante");
            txtnombreEstudiante.requestFocus();
            val = false;
//aqui se identifica si algun campo no esta lleno
            //se indicara que se debe llenar el campo 
        } else if (descripcion.length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese la descripción de la falta disciplinaria");
            txtaDescripcion.requestFocus();
            val = false;

        } else if (codigo.length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese el código del estudiante");
            txtCodigo.requestFocus();
            val = false;

        } else if (descargos.length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese los descargos del estudiante");
            txtaDescargos.requestFocus();
            val = false;
        }
        return val;
    }

    public RegistroDeAnotacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jcbFecha = new javax.swing.JComboBox<>();
        jcbTipo = new javax.swing.JComboBox<>();
        txtCodigo = new javax.swing.JTextField();
        txtnombreEstudiante = new javax.swing.JTextField();
        txtnombreDocente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDescripcion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaDescargos = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtalistado = new javax.swing.JTextArea();

        jTextField4.setText("dffffffffffffffffffffffffffffffffffffffffdfsdfsdfdfdfdfdfdfdfdfdfdfdffdfdfdfdfd");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de anotación");

        jLabel1.setText("Fecha");

        jLabel2.setText("Código del estudiante");

        jLabel3.setText("Nombre del estudiante");

        jLabel4.setText("Nombre de docente");

        jLabel5.setText("Tipo");

        jLabel6.setText("Descripción");

        jLabel7.setText("Descargos");

        jcbFecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1/1/2017", "2/1/2017", "3/1/2017", "4/1/2017" }));

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Leve", "Grave", "Gravísima" }));

        txtaDescripcion.setColumns(20);
        txtaDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtaDescripcion);

        txtaDescargos.setColumns(20);
        txtaDescargos.setRows(5);
        jScrollPane2.setViewportView(txtaDescargos);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Registro de anotación");

        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtalistado.setEditable(false);
        txtalistado.setColumns(20);
        txtalistado.setRows(5);
        jScrollPane4.setViewportView(txtalistado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtnombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jButton1)
                                                        .addGap(64, 64, 64)
                                                        .addComponent(jButton2))
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel7)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton4))
                                            .addComponent(txtnombreDocente)))
                                    .addComponent(jScrollPane4)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel8)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtnombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtnombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed
    /**
     * Asignar el botón con el método crearanotacion para poder insertar en la lista
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        listaregistro.insertarAlinicio(crearAnotacion());
        txtalistado.setText("");
        txtalistado.setText(listaregistro.listar());

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Anotacion anotacion = listaregistro.buscarAnotacion(Integer.parseInt(this.txtCodigo.getText()));
       
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * Asignar el botón con el método crearanotacion para poder actualizar en la lista
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        listaregistro.editar(crearAnotacion());
        txtalistado.setText("");
        txtalistado.setText(listaregistro.listar());

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDeAnotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDeAnotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDeAnotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDeAnotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroDeAnotacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JComboBox<String> jcbFecha;
    private javax.swing.JComboBox<String> jcbTipo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtaDescargos;
    private javax.swing.JTextArea txtaDescripcion;
    private javax.swing.JTextArea txtalistado;
    private javax.swing.JTextField txtnombreDocente;
    private javax.swing.JTextField txtnombreEstudiante;
    // End of variables declaration//GEN-END:variables
}
